
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!

target 'news' do

pod 'Alamofire' 
pod 'MJCSegmentInterface'
pod 'MJExtension'
pod 'MJRefresh'
pod ‘Kingfisher’
end
